targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    auto_apply: dependents
    build_to: cache
    runs_before:
    - source_gen|combining_builder
    applies_builders: ["source_gen|combining_builder"]
